### ISSUE TITLE
Blockcrafter-export fails with an error with Python

### ISSUE THREAD

**Issue by Shadowdane** [mapcrafter/blockcrafter#10]
[edit]   Cleaned this up as it was kind of a mess!

I got the 12 pixel texture size working in Mapcrafter with Minecraft 1.16.2, but the Mapcrafter output is way too big (~13GB) at so needed a smaller texture size which brought me to Blockcrafter from the other Issue I had posted in mapcrafter/mapcrafter#374.

I got Python working and installed the Blockcrafter package, but attempting the blockcrafter-export command fails with an error below.

```
D:\Mapcrafter\blockcrafter>pip3 install .
Processing d:\mapcrafter\blockcrafter
Requirement already satisfied: numpy in c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages (from blockcrafter==1.0) (1.19.1)
Requirement already satisfied: vispy in c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages (from blockcrafter==1.0) (0.6.4)
Requirement already satisfied: Pillow in c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages (from blockcrafter==1.0) (7.2.0)
Requirement already satisfied: freetype-py in c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages (from vispy->blockcrafter==1.0) (2.2.0)
Building wheels for collected packages: blockcrafter
  Building wheel for blockcrafter (setup.py) ... done
  Created wheel for blockcrafter: filename=blockcrafter-1.0-py3-none-any.whl size=103954 sha256=58f71d13b12468aaad8dc9148b5323e09d6b7bae20ea64cd1c9f9698d9c8ce6b
  Stored in directory: C:\Users\pweat\AppData\Local\Temp\pip-ephem-wheel-cache-hzaath6w\wheels\f9\eb\da\82a95935dbf4cb931bdf33e91866dd63328f19e60e7febeb56
Successfully built blockcrafter
Installing collected packages: blockcrafter
  Attempting uninstall: blockcrafter
    Found existing installation: blockcrafter 1.0
    Uninstalling blockcrafter-1.0:
      Successfully uninstalled blockcrafter-1.0
Successfully installed blockcrafter-1.0

D:\Mapcrafter\blockcrafter>
D:\Mapcrafter\blockcrafter>blockcrafter-export -a 1.16.2.jar -o blocks -v isometric -t 8 -r 0
WARNING: Traceback (most recent call last):
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python38\Scripts\blockcrafter-export.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 216, in main
    c = Canvas(args)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 57, in __init__
    self.show()
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 412, in _vispy_set_visible
    self.showNormal()
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 188, in on_draw
    blockstates = self.assets.blockstates
AttributeError: 'Canvas' object has no attribute 'assets'
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x1c5ff8f0850>> for DrawEvent
WARNING: QOpenGLContext::swapBuffers() called with null argument
```

**Comment by Shadowdane** [comment]
@elamperti     I gave up on the Docker option, I'll edit this post to remove that.   Working on trying to get Blockcrafter working on Python, as got a lot farther with that and actually get a crash/error.     Is there any additional details needed to diagnose the problem?    

Here is the version, installed packages and the error I'm getting.
```
D:\Mapcrafter\blockcrafter>
D:\Mapcrafter\blockcrafter>py --version
Python 3.8.5

D:\Mapcrafter\blockcrafter>
D:\Mapcrafter\blockcrafter>pip3 list
Package      Version
------------ -------
blockcrafter 1.0
freetype-py  2.2.0
numpy        1.19.1
Pillow       7.2.0
pip          20.2.2
pyglet       1.5.7
PyQt5        5.15.0
PyQt5-sip    12.8.0
QtPy         1.9.0
setuptools   47.1.0
vispy        0.6.4
wheel        0.35.1

D:\Mapcrafter\blockcrafter>
D:\Mapcrafter\blockcrafter>
D:\Mapcrafter\blockcrafter>blockcrafter-export -a 1.16.2.jar -o blocks -v isometric -t 8 -r 0
WARNING: Traceback (most recent call last):
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python38\Scripts\blockcrafter-export.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 216, in main
    c = Canvas(args)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 57, in __init__
    self.show()
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 412, in _vispy_set_visible
    self.showNormal()
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\app\backends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "c:\users\pweat\appdata\local\programs\python\python38\lib\site-packages\blockcrafter\export.py", line 188, in on_draw
    blockstates = self.assets.blockstates
AttributeError: 'Canvas' object has no attribute 'assets'
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x18b006de8b0>> for DrawEvent
WARNING: QOpenGLContext::swapBuffers() called with null argument

```

**Comment by Shadowdane** [comment]
I noticed in a different thread that Python 3.7 is supposed to be used for blockcrafter.    I just uninstalled Python 3.8 and installed Python 3.7.

The script seems gets a bit farther using Python 3.7, at least a window (VisPy canvas) opens but still crashes with the following error below.   The window stays up and I left it up for about 6hrs but nothing ever happens with it.    Previously on Python 3.8 a window would open/close instantly couldn't ever see what was popping up.     So at least it's a different result!      According to what I can see in the error seems to be crashing on a different lines compared to before.     

I hope this helps!

```
D:\Mapcrafter\blockcrafter>pip list
Package      Version
------------ -------
blockcrafter 1.0
freetype-py  2.2.0
numpy        1.19.1
Pillow       7.2.0
pip          20.2.2
pyglet       1.5.7
setuptools   47.1.0
vispy        0.6.4

D:\Mapcrafter\blockcrafter>blockcrafter-export -a 1.16.2.jar -o blocks -v isometric -t 8 -r 0
blocks\isometric_0_8.png
WARNING: Traceback (most recent call last):
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\Scripts\blockcrafter-export-script.py", line 11, in <module>
    load_entry_point('blockcrafter==1.0', 'console_scripts', 'blockcrafter-export')()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 217, in main
    app.run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 159, in _vispy_run
    return pyglet.app.run()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\base.py", line 243, in idle
    window.dispatch_event('on_draw')
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 231, in on_draw
    self.our_draw_func()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 322, in our_draw_func
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 195, in on_draw
    self.render_blocks(blockstates, texture_size, view, rotation, info_path, image_path)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 140, in render_blocks
    glblock.render(variant, actual_model, view, projection, rotation=actual_rotation, mode=mode)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 471, in render
    self.variants[variant_str] = self._load_variant(variant)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 462, in _load_variant
    for model, transformation in self.blockstate.evaluate_variant(variant):
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 477, in evaluate_variant
    model = self.assets.get_model(self.prefix + "/models/" + model_name + ".json")
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 398, in get_model
    model = Model(self, prefix, name, self._get_model_json(path))
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 370, in _get_model_json
    m = json.loads(self.source.load_file(path))
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 153, in load_file
    f = self.open_file(path)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 150, in open_file
    raise RuntimeError("Unable to find file '%s' in any source!" % path)
RuntimeError: Unable to find file 'minecraft/models/minecraft:block/acacia_button.json' in any source!
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (Pyglet) at 0x28c2600c188>> for DrawEvent
```

**Comment by Shadowdane** [comment]
So what versions does blockcrafter work on?? 

I tried running it on the 1.15.2.jar file but it fails on that too but seems to get farther in the process of doing a valid export.      It does write one file .\blocks\isometric_0_8.txt which has 1475 lines in it, but fails with the error listed below.

```
D:\Mapcrafter\blockcrafter>blockcrafter-export -a 1.15.2.jar -o blocks -v isometric -t 8 -r 0
blocks\isometric_0_8.png
INFO: Not setting data for variable vec3 a_normal; attribute is not active.
INFO: Not setting value for variable vec3 u_light_direction; uniform is not active.
INFO: Not setting value for variable int u_face_index; uniform is not active.
INFO: Not setting data for variable vec3 a_normal; attribute is not active.
INFO: Not setting value for variable vec3 u_light_direction; uniform is not active.
WARNING: Traceback (most recent call last):
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\Scripts\blockcrafter-export-script.py", line 11, in <module>
    load_entry_point('blockcrafter==1.0', 'console_scripts', 'blockcrafter-export')()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 217, in main
    app.run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 159, in _vispy_run
    return pyglet.app.run()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\app\base.py", line 243, in idle
    window.dispatch_event('on_draw')
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\window\__init__.py", line 1333, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\pweat\AppData\Roaming\Python\Python37\site-packages\pyglet\event.py", line 415, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 231, in on_draw
    self.our_draw_func()
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\app\backends\_pyglet.py", line 322, in our_draw_func
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 195, in on_draw
    self.render_blocks(blockstates, texture_size, view, rotation, info_path, image_path)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\export.py", line 140, in render_blocks
    glblock.render(variant, actual_model, view, projection, rotation=actual_rotation, mode=mode)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 471, in render
    self.variants[variant_str] = self._load_variant(variant)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 464, in _load_variant
    self.models[model.name] = Model(model)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 439, in __init__
    self.elements.append(Element(modeldef, elementdef))
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 253, in __init__
    self.faces = Element.load_faces(model, element)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\render.py", line 398, in load_faces
    f = model.load_texture(texture_name)
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 564, in load_texture
    return self.assets.load_texture(self.prefix, name + ".png")
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 414, in load_texture
    return self.source.open_file(self.texture_base.format(prefix=prefix) + "/" + path, mode="rb")
  File "C:\Users\pweat\AppData\Local\Programs\Python\Python37\lib\site-packages\blockcrafter\mcmodel.py", line 150, in open_file
    raise RuntimeError("Unable to find file '%s' in any source!" % path)
RuntimeError: Unable to find file 'minecraft/textures/entity/chest/normal_double/right_top.png' in any source!
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (Pyglet) at 0x299b1108708>> for DrawEvent
```
